export const DEBOUNCED_DELAY = 300;

export const MAX_FILE_SIZE = 4.6;
export const MONGOOSE_DUPLICATE_KEY_ERROR = 11000;

export const CONTENT_LIST_DEFAULT_PAGE_NUMBER = 1;
export const CONTENT_LIST_DEFAULT_PAGE_SIZE = 18;

export const CHAPTERS_LIST_DEFAULT_PAGE_NUMBER = 1;
export const CHAPTERS_LIST_DEFAULT_PAGE_SIZE = 18;

export const HOTTEST_CONTENT_PAGE_SIZE = 2;
export const CONTENT_LIST_PAGE_SIZE = 6;
export const FREE_READ_CONTENT_LIST_PAGE_SIZE = 9;
export const LATEST_UPDATES_CONTENT_LIST_PAGE_SIZE = 8;

export const ERROR_404_PAGE_HEADER_TITLE = "MangaToon 404 error page";
