export const DEBOUNCED_DELAY = 300;

export const MAX_FILE_SIZE = 4.6;
export const MONGOOSE_DUPLICATE_KEY_ERROR = 11000;

export const CONTENT_LIST_DEFAULT_PAGE_NUMBER = 1;
export const CONTENT_LIST_DEFAULT_PAGE_SIZE = 18;
export const HOTTEST_CONTENT_PAGE_SIZE = 2;
export const CONTENT_LIST_PAGE_SIZE = 6;
