import Head from "next/head";

import Header from "../Header";
import Navbar from "../WatchPage/Navbar";
import MobileNavLinks from "../Header/MobileHeader/MobileNavLinks";
import DesktopFooter from "../Footer/DesktopFooter";
import Footer from "../Footer";

const Layout = ({
  useContentNavbar,
  chapterTitle,
  contentTitle,
  populatedChapters,
  children,
  title,
  applyShadow,
  hideMobileLinks,
  hideFooter,
  contentPage,
}) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {useContentNavbar ? (
        <Navbar
          chapterTitle={chapterTitle}
          contentTitle={contentTitle}
          populatedChapters={populatedChapters}
        />
      ) : (
        <Header applyShadow={applyShadow} />
      )}
      {hideMobileLinks ? null : <MobileNavLinks />}
      {children}
      {hideFooter ? null : contentPage ? <DesktopFooter /> : <Footer />}
    </>
  );
};

export default Layout;
